import{a as E,S as I,i as y}from"./assets/vendor-KnZd4sWe.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();let m=1;async function L(e){const s=await E.get("https://pixabay.com/api/",{params:{key:"48985063-5c5813c169e3db6e477352dc5",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:m,per_page:40}});return m++,s}function P(){m=1}const f=document.querySelector(".gallery"),v=document.querySelector(".loader-div");document.querySelector(".end-loader-div");const C=new I(".gallery a",{captionData:"alt",captionDelay:250});function H(e){const{webformatURL:o,largeImageURL:n,tags:s,likes:t,views:r,comments:a,downloads:x}=e;return`
    <div class="image-card">
      <a href="${n}" target="_blank">
        <img src="${o}" alt="${s}" loading="lazy"/>
      </a>
      <div class="info">
        <p><strong>Likes:</strong>${t}</p>
        <p><strong>Views:</strong>${r}</p>
        <p><strong>Comments:</strong>${a}</p>
        <p><strong>Downloads:</strong>${x}</p>
      </div>
    </div>
  `}function S(e){f.innerHTML+=e.map(H).join(""),C.refresh(),u()}function M(){console.log("Done showLoader()"),f.classList.add("hidden"),v.classList.remove("hidden")}function u(){console.log("Done hideLoader()"),v.classList.add("hidden"),f.classList.remove("hidden")}function g(){y.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageLineHeight:"24px",messageColor:"#fff",maxWidth:"432px",backgroundColor:"#EF4040"})}function $(){y.show({position:"topRight",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageLineHeight:"24px",messageColor:"#fff",maxWidth:"432px",backgroundColor:"#EF4040"})}const D=document.querySelector(".form"),p=document.querySelector(".search-input"),i=document.querySelector(".load-more-btn"),b=document.querySelector(".gallery"),c=document.querySelector(".end-loader-div");let h="",l=0,d=0;D.addEventListener("submit",O);i.addEventListener("click",T);async function O(e){e.preventDefault();const o=p.value.trim();if(!o)return g();h=o,P(),p.value="",M(),z(),L(h).then(n=>{const s=n.data.hits;l=n.data.totalHits,console.log("Total hits:",l),!s||s.length===0?(g(),i.classList.add("hidden"),c.classList.add("hidden")):(S(s),w(s.length),q())}).catch(n=>{console.error("Error during image search",n),u(),g()})}async function T(){c.classList.remove("hidden"),L(h).then(e=>{const o=e.data.hits;if(l=e.data.totalHits,console.log("Total hits:",l),!o||o.length===0){c.classList.add("hidden"),i.classList.add("hidden");return}S(o),w(o.length),q()}).catch(e=>{console.error("Error during image load more",e),u(),g()})}function w(e){b.querySelectorAll(".image-card").length>=l?(i.classList.add("hidden"),c.classList.add("hidden"),$()):(i.classList.remove("hidden"),c.classList.add("hidden"))}function z(){const e=document.querySelector(".gallery");e.innerHTML="",u()}function q(){const e=b.querySelector(".image-card");e&&!d&&(d=e.getBoundingClientRect().height),d&&window.scrollBy({top:d*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
